sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-1.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-2.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-3.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-4.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-5.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-6.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-7.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-8.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-9.local 'pkill java'
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-10.local 'pkill java'
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-11.local 'pkill java'
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-12.local 'pkill java'
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-13.local 'pkill java'
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-14.local 'pkill java'
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-15.local 'pkill java'
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-16.local 'pkill java'

