sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-1.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.10 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'&
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-2.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.3 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-3.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.16 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-4.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.14 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-5.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.4 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-6.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.6 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-7.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.18 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-8.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.8 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-9.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.20 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'&
sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-10.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.35 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-11.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.9 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-12.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.16 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-13.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.13 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-14.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.18 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-15.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.12 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
# sudo ssh -o 'StrictHostKeyChecking no' root@morge-smac-cluster-16.local 'mkdir /mnt/results; sudo chown centos /mnt/results; cd /home/centos/; rm /home/centos/logAdaptive.txt; ulimit -Hs; java -Xms100G -Xmx100G -jar daemon.jar TestRemote 192.168.1.19 6666 2>&1 | tee -a /home/centos/logAdaptive.txt'& 
